version: '3.8'

services:
  php:
    build:
      dockerfile: ./docker/PHP/Dockerfile
    working_dir: /app
    volumes:
      - './:/app'
    container_name: portfolio-php
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    ports:
      - 8080:80
    links:
      - 'php'
    working_dir: /app
    volumes:
      - './:/app'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: postgres
    volumes:
      - './app:/app'
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"


volumes:
  postgres-data:
    external: true